version: '3.7'
services:
  kontext:
    build: .
    command: bash -c "cp -r /opt/kontext/public/files/* /opt/kontext/public/share && gunicorn -c ./scripts/install/conf/docker/gunicorn-conf.py public.app:application"
    environment:
      - STATUS_SERVICE_URL=${STATUS_SERVICE_URL}
    volumes:
      - ./scripts/install/conf/docker/config.xml:/opt/kontext/conf/config.xml
      - files:/opt/kontext/public/share
      - corpora:/var/local/corpora
    networks:
      - redis
      - kontext
    depends_on: 
      - redis
  redis:
    image: redis:latest
    networks:
      - redis
    ports:
      - "16379:6379"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./scripts/install/conf/docker/${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf
      - files:/opt/kontext/public/files
    networks:
      - kontext
    depends_on:
      - kontext
      - ws
  rq-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.rqscheduler
    networks:
      - redis
    depends_on: 
      - redis
      - kontext
  rq-worker:
    build:
      context: .
      dockerfile: Dockerfile.rqworker
    volumes:
      - ./scripts/install/conf/docker/config.xml:/opt/kontext/conf/config.xml
      - corpora:/var/local/corpora
    networks:
      - redis
    depends_on:
      - redis
      - kontext
  ws:
    build:
      context: .
      dockerfile: Dockerfile.ws
    command: python3 public/ws_app.py --host 0.0.0.0 --log debug
    volumes:
      - ./scripts/install/conf/docker/config.xml:/opt/kontext/conf/config.xml
      - corpora:/var/local/corpora
    networks:
      - redis
      - kontext
    depends_on: 
      - redis
      - kontext
volumes:
  files:
  corpora:
networks:
  redis: {}
  kontext: {}