name: Kontext installation test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-versions: [3.6]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-versions }}
    - name: Install kontext (test mode)
      run: |
        sudo su
        python scripts/install/install.py --test